import pandas as pd
import re
from tqdm import tqdm
from typing import Optional, Dict

def parse_aqua_options(question: str) -> Dict[str, str]:
    matches = re.findall(r"([A-E])\)\s*([^\s]+)", question)
    return {letter: value for letter, value in matches}


def extract_last_number(text: str) -> Optional[str]:
    nums = re.findall(r"-?\d+(?:\.\d+)?", text)
    return nums[-1] if nums else None


def extract_final_letter(model_output: str, question: str) -> Optional[str]:
    """
    Returns:
        Single character string (e.g., "A", "B", ...) or None
    """

    # -----------------------------------
    # 1. Full format: Final Answer: 'C'. '42'
    # -----------------------------------
    match = re.search(
        r"Final\s*Answer\s*:\s*['\"]?([A-E])['\"]?\s*\.\s*['\"]?-?\d+(?:\.\d+)?['\"]?",
        model_output,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1).upper()

    # -----------------------------------
    # 2. Letter-only format: Final Answer: C
    # -----------------------------------
    match = re.search(
        r"Final\s*Answer\s*:\s*['\"]?([A-E])['\"]?",
        model_output,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1).upper()

    # -----------------------------------
    # 3. Backup: last number → map to options
    # -----------------------------------
    last_num = extract_last_number(model_output)
    if last_num:
        options = parse_aqua_options(question)
        for letter, value in options.items():
            if value == last_num:
                return letter
    print("failed to extract")
    return "fail"


# The two dataframes below are generated by running Llama 3.1 8B Instruct and 
# Llama 3.3 70B Versatile (I believe this is the same as the instruct version)
# on GSM8K and MATH train questions.
# I run Llama 8B locally (see gsm8k_local.py & MATH_local.py) and Llama 70B is accessed via groq API 
# (see groq's website) and gsm8k_groq.py, MATH_groq.py for implementations.
aqua_l8 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/AQUA_Llama_8B_train.csv")
aqua_l70 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/AQUA_L70_train.csv")

aqua_big_df = aqua_l8.merge(aqua_l70, on="Question")

print(aqua_big_df.columns)
aqua_big_df = aqua_big_df.drop("Unnamed: 0_x", axis=1)
aqua_big_df = aqua_big_df.drop("Unnamed: 0_y", axis=1)
aqua_big_df = aqua_big_df.drop("Correct Answer_y", axis=1)

aqua_big_df["dataset"] = "aqua"
print(aqua_big_df.columns)

aqua_big_df = aqua_big_df.rename(columns={
    "Correct Answer_x": "Answer",
    "Llama_8B Full": "l8",
    "L70 Full": "l70"
})

print(aqua_big_df.columns)


df_og = aqua_big_df


questions = df_og["Question"].to_list()

answers = df_og["Answer"].to_list()
l8_full = df_og["l8"].to_list()
l70_full = df_og["l70"].to_list()
dataset = df_og["dataset"].to_list()


lean_l8 = []
lean_l70 = []

l8_on_cor_l70_on_incor = []

l = 0

l8_fail = 0
l70_fail = 0
target_fail =0

for q, ans, l8, l70, ds in tqdm(zip(questions, answers, l8_full, l70_full, dataset),total=len(questions), desc = "Running..."):
    l+=1

    
    
    l8_ans = extract_final_letter(l8, q)

    if l8_ans == "fail":
        l8_fail +=1
    l70_ans = extract_final_letter(l70, q)
    if l70_ans == "fail":
        l70_fail +=1
    target = ans
    

    if (l70_ans == target) and (l8_ans == target):
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(1)
    elif (l70_ans == target):
        lean_l8.append(0)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)
    elif (l8_ans == target):
        lean_l8.append(1)
        lean_l70.append(1)
        l8_on_cor_l70_on_incor.append(1)
    else:
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)



df_labeled = df_og
df_labeled["full_lean_l8"] = lean_l8
df_labeled["full_lean_l70"] = lean_l70
df_labeled["lean_l8_on_cor_lean_l70_on_incor"] = l8_on_cor_l70_on_incor


print("\nSTATS SUMMARY\n")
print(f"lean_l8 route to L8 {sum(lean_l8)/l}")
print(f"lean_l70 route to L8 {sum(lean_l70)/l}")
print(f"lean_l8_on_cor_lean_l70_on_incor route to L8: {sum(l8_on_cor_l70_on_incor)/l}")

print(l8_fail)
print(l70_fail)
print(target_fail)

df_labeled.to_csv("HLLM_train_AQuA.csv", index=False)




