import pandas as pd
import re
from grading import grader
from tqdm import tqdm


def extract_final_answer(model_resp):
    """Extract the last numerical answer from model response"""
    # Remove commas so for example 5,000 becomes 5000
    model_resp = model_resp.replace(",", "")
    # Find the last number
    extracted_num = re.findall(r"-?\d+\.?\d*", model_resp)
    if extracted_num:
        return float(extracted_num[-1])
    else:
        return "NA"
    


def extract_math_ans(true_ans):
    true_ans = str(true_ans)
    init = len(true_ans) - 1 
    targ_len = len("\\boxed")
    final_ans = ""
    
    # Find the position of "\boxed"
    while (init - targ_len) >= 0:
        if true_ans[init - targ_len: init] == "\\boxed":
            break
        init -= 1
    if init - targ_len < 0:  # If "\boxed" is not found
        return "NA"

    # Locate the opening "{"
    start = init
    while start < len(true_ans) and true_ans[start] != "{":
        start += 1
    if start == len(true_ans):
        return "NA"  # No opening brace found

    # Extract the content inside \boxed{...}
    start += 1  # Move past '{'
    brackets = 1
    for i in range(start, len(true_ans)):
        if true_ans[i] == "{":
            brackets += 1
        elif true_ans[i] == "}":
            brackets -= 1
            if brackets == 0:
                return final_ans  # Stop when the last closing '}' is found
        final_ans += true_ans[i]

    return "NA"  # If it reaches here, something went wrong

    
def eq(a, b):
    return grader.grade_answer(a, b)

# The two dataframes below are generated by running Llama 3.1 8B Instruct and 
# Llama 3.3 70B Versatile (I believe this is the same as the instruct version)
# on GSM8K and MATH train questions.
# I run Llama 8B locally (see gsm8k_local.py & MATH_local.py) and Llama 70B is accessed via groq API 
# (see groq's website) and gsm8k_groq.py, MATH_groq.py for implementations.
gsm8k_l8 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/original_data/GSM8K_training_l8.csv")
gsm8k_l70 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/original_data/GSM8K_training_llama_70b_full.csv")

gsm8k_big_df = gsm8k_l8.merge(gsm8k_l70, on="Question")
gsm8k_big_df = gsm8k_big_df.drop("Unnamed: 0", axis=1)
gsm8k_big_df = gsm8k_big_df.drop("Correct Answer_y", axis=1)

gsm8k_big_df["dataset"] = "gsm8k"

gsm8k_big_df = gsm8k_big_df.rename(columns={
    "Correct Answer_x": "Answer",
    "Baseline Full_x": "l8",
    "Baseline Full_y": "l70"
})

print(gsm8k_big_df.columns)

math_l8 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/original_data/MATH_train_l8.csv")
math_l70 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/original_data/MATH_train_llama_70B_groq.csv")

math_big_df = math_l8.merge(math_l70, on="Question")
math_big_df = math_big_df.drop("Unnamed: 0_x", axis=1)
math_big_df = math_big_df.drop("Unnamed: 0_y", axis=1)
math_big_df = math_big_df.drop("Correct Answer_y", axis=1)

math_big_df["dataset"] = "math"

math_big_df = math_big_df.rename(columns={
    "Correct Answer_x": "Answer",
    "Llama8B SC (1)": "l8",
    "Llama3.1-8B SC (1)" : "l70"
})

# big_df = pd.concat([gsm8k_big_df, math_big_df], ignore_index=True)


# big_df.to_csv("HLLM_train_OG.csv")

# df_og = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/HLLM_train_OG.csv")
df_og = math_big_df


questions = df_og["Question"].to_list()

answers = df_og["Answer"].to_list()
l8_full = df_og["l8"].to_list()
l70_full = df_og["l70"].to_list()
dataset = df_og["dataset"].to_list()


lean_l8 = []
lean_l70 = []

l8_on_cor_l70_on_incor = []

l = 0

for q, ans, l8, l70, ds in tqdm(zip(questions, answers, l8_full, l70_full, dataset),total=len(questions), desc = "Running..."):
    l+=1

    
    # if ds =="gsm8k":
    #     l8_ans = extract_final_answer(l8)
    #     l70_ans = extract_final_answer(l70)
    #     target = extract_final_answer(ans)
        
    #     if l70_ans == target and l8_ans == target:
    #         lean_l8.append(1)
    #         lean_l70.append(0)
    #         l8_on_cor_l70_on_incor.append(1)
    #     elif l70_ans == target:
    #         lean_l8.append(0)
    #         lean_l70.append(0)
    #         l8_on_cor_l70_on_incor.append(0)
    #     elif l8_ans == target:
    #         lean_l8.append(1)
    #         lean_l70.append(1)
    #         l8_on_cor_l70_on_incor.append(1)
    #     else:
    #         lean_l8.append(1)
    #         lean_l70.append(0)
    #         l8_on_cor_l70_on_incor.append(0)

        
    # else:
    l8_ans = extract_math_ans(l8)
    l70_ans = extract_math_ans(l70)
    target = extract_math_ans(ans)

    if eq(l70_ans, target) and eq(l8_ans, target):
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(1)
    elif eq(l70_ans, target):
        lean_l8.append(0)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)
    elif eq(l8_ans, target):
        lean_l8.append(1)
        lean_l70.append(1)
        l8_on_cor_l70_on_incor.append(1)
    else:
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)



df_labeled = df_og
df_labeled["full_lean_l8"] = lean_l8
df_labeled["full_lean_l70"] = lean_l70
df_labeled["lean_l8_on_cor_lean_l70_on_incor"] = l8_on_cor_l70_on_incor


print("\nSTATS SUMMARY\n")
print(f"lean_l8 route to L8 {sum(lean_l8)/l}")
print(f"lean_l70 route to L8 {sum(lean_l70)/l}")
print(f"lean_l8_on_cor_lean_l70_on_incor route to L8: {sum(l8_on_cor_l70_on_incor)/l}")

df_labeled.to_csv("HLLM_train_MATH.csv", index=False)




