import pandas as pd
import re
from tqdm import tqdm
from datasets import  load_dataset 

def input_dataset(data_name, version = ""):
    if version == "":
        dataset = load_dataset(data_name)
    else:
        dataset = load_dataset(data_name,version)
    return dataset

def extract_ans(text):
    lines = text.strip().splitlines()
    
    # Iterate backwards to find the first non-empty line
    for line in reversed(lines):
        if line.strip():  # Non-empty after stripping spaces
            return line.strip()
    
    return None  # No non-empty lines found

def preprocess_options(options):
    otp = []
    for i, j in zip(options["label"], options["text"]):
        x = f"{i}. {j}"
        otp.append(x)
    return otp

def ans_proc(full_ans, options):
    flag = False
    letters = options["label"]
    words = options["text"]
    last_line = extract_ans(full_ans)

    for x, j in enumerate(words):
        if j.lower() in last_line.lower():
            ans = letters[x]
            flag = True
            break
    if flag == False:
        for j in reversed(letters):
            if j in last_line:
                ans = j
                flag = True
                break
    if flag == False:
        ans = "NA"
    return ans

def ans_proc_2(full_ans, options):
    letters = options["label"]
    words = options["text"]

    # 0. Try to directly read a letter from a "Final Answer" pattern anywhere
    #    Example: Final Answer: 'A'. 'bank'
    m = re.search(
        r"[Ff]inal\s*Answer[^A-Za-z0-9]*['\"]?\s*([A-Z])\s*['\"]?", 
        full_ans
    )
    if m:
        letter = m.group(1)
        if letter in letters:
            return letter

    # 1. Fallback: use your previous behavior on the last non-empty line
    last_line = extract_ans(full_ans)
    flag = False

    # Try to match by option text first
    for x, j in enumerate(words):
        if j.lower() in last_line.lower():
            ans = letters[x]
            flag = True
            break

    # If no text match, try to match by label letter
    if not flag:
        for j in reversed(letters):
            if j in last_line:
                ans = j
                flag = True
                break

    if not flag:
        ans = "NA"

    return ans


# The two dataframes below are generated by running Llama 3.1 8B Instruct and 
# Llama 3.3 70B Versatile (I believe this is the same as the instruct version)
# on GSM8K and MATH train questions.
# I run Llama 8B locally (see gsm8k_local.py & MATH_local.py) and Llama 70B is accessed via groq API 
# (see groq's website) and gsm8k_groq.py, MATH_groq.py for implementations.
dfl8 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/CSQA_llama8B_train.csv")
dfl70 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/CSQA_train_L70.csv")

csqa_big_df = dfl8.merge(dfl70, on="Question")

# print(csqa_big_df.columns)
csqa_big_df = csqa_big_df.drop("Unnamed: 0_x", axis=1)
csqa_big_df = csqa_big_df.drop("Unnamed: 0_y", axis=1)
csqa_big_df = csqa_big_df.drop("Correct Answer", axis=1)
# print(csqa_big_df.columns)

print(csqa_big_df.columns)

csqa_big_df = csqa_big_df.rename(columns={
    "Llama8B": "l8",
    "L70": "l70"
})

print(csqa_big_df.columns)


df_og = csqa_big_df


questions = df_og["Question"].to_list()

answers = df_og["Answer"].to_list()
l8_full = df_og["l8"].to_list()
l70_full = df_og["l70"].to_list()
df_og["dataset"] = "csqa"
dataset = df_og["dataset"].to_list()


lean_l8 = []
lean_l70 = []

l8_on_cor_l70_on_incor = []

l = 0

l8_fail = 0
l70_fail = 0
target_fail =0

dataset=input_dataset("tau/commonsense_qa")
opts = dataset['train']['choices']
print(len(questions))
print(len(answers))
print(len(l8_full))
print(len(l70_full))
print(len(opts))
df_og["dataset"] = "csqa"
dataset = df_og["dataset"].to_list()
print(len(dataset))
# questions = dataset['validation']['question']
# targets = dataset['validation']['answerKey']


for q, ans, l8, l70, opts_curr, ds in tqdm(zip(questions, answers, l8_full, l70_full, opts, dataset),total=len(questions), desc = "Running..."):
    l+=1
    target = str(ans)
    l8_ans = ans_proc(l8, opts_curr)

    if l8_ans == "fail":
        l8_fail +=1
    l70_ans = ans_proc(l70, opts_curr)
    if l70_ans == "fail":
        l70_fail +=1
    target = ans
    

    if (l70_ans == target) and (l8_ans == target):
        
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(1)
    elif (l70_ans == target):
        
        lean_l8.append(0)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)
    elif (l8_ans == target):
        
        lean_l8.append(1)
        lean_l70.append(1)
        l8_on_cor_l70_on_incor.append(1)
    else:
        
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)



df_labeled = df_og
df_labeled["full_lean_l8"] = lean_l8
df_labeled["full_lean_l70"] = lean_l70
df_labeled["lean_l8_on_cor_lean_l70_on_incor"] = l8_on_cor_l70_on_incor


print("\nSTATS SUMMARY\n")
print(f"lean_l8 route to L8 {sum(lean_l8)/l}")
print(f"lean_l70 route to L8 {sum(lean_l70)/l}")
print(f"lean_l8_on_cor_lean_l70_on_incor route to L8: {sum(l8_on_cor_l70_on_incor)/l}")



df_labeled.to_csv("HLLM_train_CSQA.csv", index=False)




