import pandas as pd
import re
from tqdm import tqdm
from datasets import  load_dataset 

def input_dataset(data_name, version = ""):
    if version == "":
        dataset = load_dataset(data_name)
    else:
        dataset = load_dataset(data_name,version)
    return dataset


def extract_sqa(text):
    clean_text = re.sub(r'\s+', ' ', text.strip().lower())

    match = re.search(r'final\s*answer\s*[:\-]?\s*(true|false|1|0)', clean_text, flags=re.IGNORECASE)
    if not match:
        print("[extract_final_answer] Error: could not find a valid final answer (True/False/1/0).")
        return None

    value = match.group(1)
    if value in ['true', '1']:
        return True
    elif value in ['false', '0']:
        return False
    else:
        print("[extract_final_answer] Error: unrecognized final answer format.")
        return None

def extract_sqa2(text):
    lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
    if not lines:
        print("nothing found")
        return None
    last_line = lines[-1].lower()
    if "true" in last_line:
        return True
    elif "false" in last_line:
        return False
    else:
        print("nothing found")
        return -1


# The two dataframes below are generated by running Llama 3.1 8B Instruct and 
# Llama 3.3 70B Versatile (I believe this is the same as the instruct version)
# on GSM8K and MATH train questions.
# I run Llama 8B locally (see gsm8k_local.py & MATH_local.py) and Llama 70B is accessed via groq API 
# (see groq's website) and gsm8k_groq.py, MATH_groq.py for implementations.
dfl8 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/StrategyQA_l8_train_with_ev.csv")
dfl70 = pd.read_csv("/home/tmalik6/LLMR/Code/hllm/training_data/StrategyQA_l70_we_train.csv")

big_df = dfl8.merge(dfl70, on="Question")

print(big_df.columns)
big_df = big_df.drop("Unnamed: 0_x", axis=1)
big_df = big_df.drop("Unnamed: 0_y", axis=1)
big_df = big_df.drop("Correct Answer_x", axis=1)
print(big_df.columns)

# print(csqa_big_df.columns)

big_df = big_df.rename(columns={
    "Llama8b 0": "l8",
    "Llama70B SC (1)": "l70",
    "Correct Answer_y": "Answer"
})

# print(big_df.columns)


df_og = big_df


questions = df_og["Question"].to_list()

answers = df_og["Answer"].to_list()
l8_full = df_og["l8"].to_list()
l70_full = df_og["l70"].to_list()
df_og["dataset"] = "SQA"
dataset = df_og["dataset"].to_list()


lean_l8 = []
lean_l70 = []

l8_on_cor_l70_on_incor = []

l = 0

l8_fail = 0
l70_fail = 0
target_fail =0

# dataset=input_dataset("tau/commonsense_qa")
# opts = dataset['train']['choices']
# print(len(questions))
# print(len(answers))
# print(len(l8_full))
# print(len(l70_full))
# print(len(opts))
# df_og["dataset"] = "csqa"
# dataset = df_og["dataset"].to_list()
# print(len(dataset))
# questions = dataset['validation']['question']
# targets = dataset['validation']['answerKey']


for q, ans, l8, l70, ds in tqdm(zip(questions, answers, l8_full, l70_full, dataset),total=len(questions), desc = "Running..."):
    l+=1
    target = str(ans)

    l8_ans = extract_sqa2(l8)
    if l8_ans == "fail":
        l8_fail +=1

    l70_ans = extract_sqa2(l70)
    if l70_ans == "fail":
        l70_fail +=1
    target = ans
    

    if (l70_ans == target) and (l8_ans == target):
        
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(1)
    elif (l70_ans == target):
        
        lean_l8.append(0)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)
    elif (l8_ans == target):
        
        lean_l8.append(1)
        lean_l70.append(1)
        l8_on_cor_l70_on_incor.append(1)
    else:
        
        lean_l8.append(1)
        lean_l70.append(0)
        l8_on_cor_l70_on_incor.append(0)



df_labeled = df_og
df_labeled["full_lean_l8"] = lean_l8
df_labeled["full_lean_l70"] = lean_l70
df_labeled["lean_l8_on_cor_lean_l70_on_incor"] = l8_on_cor_l70_on_incor


print("\nSTATS SUMMARY\n")
print(f"lean_l8 route to L8 {sum(lean_l8)/l}")
print(f"lean_l70 route to L8 {sum(lean_l70)/l}")
print(f"lean_l8_on_cor_lean_l70_on_incor route to L8: {sum(l8_on_cor_l70_on_incor)/l}")



df_labeled.to_csv("HLLM_train_SQA_WE.csv", index=False)




